# Overrides COLOR_LOWER_LIMIT and COLOR_UPPER_LIMIT environment variables
# to filter for blue objects
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base/

patches:
- target:
    kind: StatefulSet
    name: color
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: "94,171,156"
    - op: replace
      path: /spec/template/spec/containers/0/env/1/value
      value: "106,239,246"
